### PR TITLE
usability goals for integration tests PR

### LINKED ISSUE #257: usability goals for integration tests
- [ ] develop a way to see which test file is currently being run by `tape`, clearly marked out in the TAP output
- [ ] make tests more isolated from each other so that some can continue even if others fail
- [ ] use `tap-dot` or something similar to provide a better summary at the end of the test running about what happened, and which tests passed and which failed

### PR DESCRIPTION
**Pull request by Connoropolous**
Trying to fix #257 
This is preliminary work towards #216.

Goal of this PR is to make the test output, and runners, more usable, and clear

### CODE REVIEW

File: test/economic-resource/resource_logic.js [hunk 1]
```diff
@@ -20,6 +20,17 @@ const testEventProps = {
 runner.registerScenario('EconomicResource & EconomicEvent record interactions', async (s, t) => {
   const { cells: [observation, specification] } = await buildPlayer(s, config, ['observation', 'specification'])
 
+  // HACK: this prevents a flaky issue
```
Comment (pospi) [inline test/economic-resource/resource_logic.js]: Have you reinstalled modules since encountering this issue? After bfde90bd we should no longer be hitting these intermittent timeouts. Unless you have a *really* slow machine... I guess increasing the timeout again is a possibility. But I would try ensuring you have the patch active and see if it resolves things.

**Comment by pospi** [comment]
Glad to have found the recursion fix- yeah, there may occasionally be `EconomicEvents` logged against an `EconomicResource` which don't actually result in updating the state of the resource (eg. during stocktake if the discovered inventory count is as expected, you might not change anything but still log an `action: raise` with a quantity of 0 just to state that the observation was made and double-checked).

**Comment by pospi** [comment]
A couple of things about the integration test shell script-

I don't see it as terribly worthwhile to add, especially given that more test folders will be added in future. It's just another file to keep in sync with other parts of the repo and the only real benefit is printing out lines about which tests are executing. Once they're all passing we will expect the whole suite to run in one command and TAP output will tell us everything we need to know, so it seems like an unnecessary addition to me.

Also to note that the test numbers you're seeing are in no way accurate. The ones with very low assertion counts are just failing before execution begins and so the runner can't pick up anything following where the script crashes. Once we make API updates for the latest Tryorama they will proceed past the initialisation and you will start to see much higher numbers in the TAP output.

**Comment by Connoropolous** [comment]
> Glad to have found the recursion fix- yeah, there may occasionally be `EconomicEvents` logged against an `EconomicResource` which don't actually result in updating the state of the resource (eg. during stocktake if the discovered inventory count is as expected, you might not change anything but still log an `action: raise` with a quantity of 0 just to state that the observation was made and double-checked).

Yeah, I've gathered that now. Makes sense.

File: test/economic-resource/resource_logic.js (hunk 1 above)
Comment (Connoropolous) [reply test/economic-resource/resource_logic.js]: It's not a timeout, it seems like a race condition.

**Comment by Connoropolous** [comment]
There are two objectives I have: 

- make it easy to run a specific, individual test file (my script doesn't accomplish this really yet. recommendations for how to do that?)
- make it easy to see which results are associated with which test file. The TAP output seems not useful at all for that, even with tap-dot

**Comment by Connoropolous** [comment]
I hotfixed in to `sprout` branch the `get_latest_header_hash` fix, which fixes the Economic Resource tests, so now this PRs only diff is related to test running

File: test/economic-resource/resource_logic.js (hunk 1 above)
Comment (Connoropolous) [reply test/economic-resource/resource_logic.js]: Ah, it manifested in an unexpected way. You're right that those things were related. It didn't seem to me like they could be. I would remove these again

**Comment by Connoropolous** [comment]
I've deleted the script, and for now, reduced this PR to a change from `faucet` to `tap-dot` to achieve the intended goal of receiving a better summary of things at the end of a test run

**Review by pospi — APPROVED** [review]
