### PR TITLE
check if unit types match before updating resource

### LINKED ISSUE #355: omiting unitId (or passing the wrong one) in economic events for resources that have a specified unitId throws a very dense error
This occurs when you try to call `createEconomicEvent` with a `transfer` action and you don't pass in the `unitId` 

```
Uncaught (in promise) Error: Unexpected error value:
{ type: "error", data: { type: "ribosome_error", data: "Wasm runtime error while working with Ribosome: RuntimeError: 
WasmError { file: \"lib/hdk_records/src/lib.rs\", line: 111, error: Guest(\"Error in remote call 
WasmError { file: \\\"/Users/connor/.cargo/registry/src/github.com-1ecc6299db9ec823/holochain-0.0.152/src/core/ribosome/host_fn/call.rs\\\", line: 141, 
error: Host(\\\"Wasm runtime error while working with Ribosome: RuntimeError: 
WasmError { file: \\\\\\\"/Users/connor/.cargo/registry/src/github.com-1ecc6299db9ec823/holochain_wasmer_host-0.0.80/src/guest.rs\\\\\\\", line: 259, 
error: CallError(\\\\\\\"RuntimeError: unreachable\\\\\\\") }\\\") }\") }" } }
```

### PR DESCRIPTION
**Pull request by weswalla**
closes #355

### CODE REVIEW

File: lib/vf_measurement/src/lib.rs [hunk 1]
```diff
@@ -40,22 +42,26 @@ impl<'a> QuantityValue {
...
 
-pub fn add(q1: QuantityValue, q2: QuantityValue) -> QuantityValue {
+pub fn add(q1: QuantityValue, q2: QuantityValue) -> RecordAPIResult<QuantityValue> {
     if q1.has_unit != q2.has_unit {
-        panic!("Unimplemented! Need to enable unit conversions in QuantityValue math");
-    }
-    QuantityValue {
-        has_numerical_value: q1.has_numerical_value + q2.has_numerical_value,
-        has_unit: q1.has_unit,
+        return Err(DataIntegrityError::Wasm(wasm_error!(WasmErrorInner::Guest(format!("Mismatching unit types. Trying to add {:?} with {:?}", q1.get_unit(), q2.get_unit()))).into()));
```
Comment (Connoropolous) [inline lib/vf_measurement/src/lib.rs]: another option here to improve on the resulting error formatting in the client, is to add a specific error variant to DataIntegrityError. Looking at the variants, you can get a sense how it interpolates variables into the error message. I'd like to see this one thing changed.

File: lib/vf_measurement/src/lib.rs [hunk 2]
```diff
@@ -40,22 +42,26 @@ impl<'a> QuantityValue {
...
 
-pub fn subtract(q1: QuantityValue, q2: QuantityValue) -> QuantityValue {
+pub fn subtract(q1: QuantityValue, q2: QuantityValue) -> RecordAPIResult<QuantityValue> {
     if q1.has_unit != q2.has_unit {
-        panic!("Unimplemented! Need to enable unit conversions in QuantityValue math");
-    }
-    QuantityValue {
-        has_numerical_value: q1.has_numerical_value - q2.has_numerical_value,
-        has_unit: q1.has_unit,
+        return Err(DataIntegrityError::Wasm(wasm_error!(WasmErrorInner::Guest(format!("Mismatching unit types. Trying to subtract {:?} with {:?}", q1.get_unit(), q2.get_unit()))).into()));
```
Comment (Connoropolous) [inline lib/vf_measurement/src/lib.rs]: same thing here

File: zomes/rea_economic_resource/lib/src/lib.rs [hunk 3]
```diff
@@ -128,8 +127,9 @@ impl API for EconomicResourceZomePermissableDefault {
         // if the event is a transfer-like event, run the receiver's update first
         if let MaybeUndefined::Some(receiver_inventory) = &event.to_resource_inventoried_as {
             let inv_entry_hash: &EntryHash = receiver_inventory.as_ref();
+
             let (meta, resource_address, new_resource, prev_resource) = handle_update_inventory_resource(
-                &get_latest_action_hash(inv_entry_hash.clone())?,   // :TODO: temporal reduction here! Should error on mismatch and return latest valid ID
```
Comment (Connoropolous) [inline zomes/rea_economic_resource/lib/src/lib.rs:132]: I am wondering about the removal of the TODO, and TBH trying to understand it. 
Do we know if that issue is legit resolved now?

**Review by Connoropolous — CHANGES_REQUESTED** [review]
Everything worked in pretty nicely here! 
The tests seems to be failing on the basis of the simultaneous test-running issues (too many entries returned). Do the tests all pass locally?
Just a recommendation on the error

**Review by Connoropolous — APPROVED** [review]

**Review by Connoropolous — APPROVED** [review]
