### PR TITLE
fix stringIdRegex for matching unit identifiers so that it catches symbols and any non-digits

### LINKED ISSUE #354: stringIdRegex for Unit symbols is not loose enough for something like `$`
https://github.com/h-REA/hREA/blob/067ee13467a304140ca62deec084d7a4cfa7c6dc/modules/vf-graphql-holochain/connection.ts#L142

this regex doesn't pick up, and thus doesn't deserialize for zome calls, a Unit ID which is specified via an actual 'symbol' symbol, instead of a string. @pospi I am guessing this is not intentional

### PR DESCRIPTION
**Pull request by Connoropolous**
closes #354

### CODE REVIEW

File: modules/vf-graphql-holochain/connection.ts [hunk 1]
```diff
@@ -139,7 +139,11 @@ const HOLOHASH_PREFIX_AGENT = [0x84, 0x20, 0x24]   // uhCAk
 
 const serializedHashMatchRegex = /^[A-Za-z0-9_+\-/]{53}={0,2}$/
 const idMatchRegex = /^[A-Za-z0-9_+\-/]{53}={0,2}:[A-Za-z0-9_+\-/]{53}={0,2}$/
-const stringIdRegex = /^\w+?:[A-Za-z0-9_+\-/]{53}={0,2}$/
+// something like
+// $:uhC0k1mcUqQIbtT0mkdTldhBaAvR6KlKxIV2IYwJemHt-NO92uXG5
+// or kg:uhC0k1mcUqQIbtT0mkdTldhBaAvR6KlKxIV2IYwJemHt-NO92uXG5
+// but not 9:uhC0k1mcUqQIbtT0mkdTldhBaAvR6KlKxIV2IYwJemHt-NO92uXG5 (i.e. no digits in the id)
+const stringIdRegex = /^\D+?:[A-Za-z0-9_+\-/]{53}={0,2}$/
```
Comment (weswalla) [inline modules/vf-graphql-holochain/connection.ts:146]: I'm unsure what the `_+\-/` section is meant to capture, but since that hasn't changed in this commit I'm assuming its okay.

**Review by weswalla — APPROVED** [review]

File: modules/vf-graphql-holochain/connection.ts (hunk 1 above)
Comment (pospi) [reply modules/vf-graphql-holochain/connection.ts:146]: it's just the base64 encoding that gets done, I believe those are valid characters.

**Review by pospi — APPROVED** [review]
